import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import { Download, FileText, Image, FileSpreadsheet, MessageCircle, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { format } from 'date-fns';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  timeframe: string;
  selectedData: any;
}

export const AnalyticsExportModal = ({ 
  isOpen, 
  onClose, 
  timeframe, 
  selectedData 
}: ExportModalProps) => {
  const [exportFormat, setExportFormat] = useState<'pdf' | 'png' | 'excel' | 'summary'>('pdf');
  const [exportOptions, setExportOptions] = useState({
    includeCharts: true,
    includeKPIs: true,
    includeTrends: true,
    includeInsights: true,
    includeRawData: false
  });
  const [isExporting, setIsExporting] = useState(false);

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('id-ID', {
      style: 'currency',
      currency: 'IDR',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);
  };

  const handleExport = async () => {
    setIsExporting(true);
    try {
      switch (exportFormat) {
        case 'pdf':
          await generatePDFReport();
          break;
        case 'png':
          await exportChartsAsPNG();
          break;
        case 'excel':
          await generateExcelReport();
          break;
        case 'summary':
          await generateBusinessSummary();
          break;
      }
      toast.success('Export completed successfully!');
      onClose();
    } catch (error: any) {
      toast.error(`Export failed: ${error.message}`);
    } finally {
      setIsExporting(false);
    }
  };

  const generatePDFReport = async () => {
    const doc = new jsPDF();
    
    doc.text("Analytics Report", 14, 22);
    doc.setFontSize(11);
    doc.text(`Period: ${timeframe}`, 14, 30);
    doc.text(`Generated on: ${format(new Date(), 'dd MMM yyyy HH:mm')}`, 14, 36);

    autoTable(doc, {
      startY: 50,
      head: [['Metric', 'Value']],
      body: [
        ['Total Revenue', formatCurrency(selectedData?.totalRevenue || 0)],
        ['Total Profit', formatCurrency(selectedData?.totalProfit || 0)],
        ['Profit Margin', `${(selectedData?.profitMargin || 0).toFixed(1)}%`],
        ['Total Transactions', (selectedData?.totalTransactions || 0).toLocaleString()],
      ],
    });

    doc.save(`analytics-report-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
  };

  const exportChartsAsPNG = async () => {
    toast.info('Chart export functionality would be implemented with html2canvas library');
  };

  const generateExcelReport = async () => {
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.json_to_sheet([
      { Metric: "Total Revenue", Value: selectedData?.totalRevenue || 0 },
      { Metric: "Total Profit", Value: selectedData?.totalProfit || 0 },
      { Metric: "Profit Margin", Value: `${(selectedData?.profitMargin || 0).toFixed(1)}%` },
      { Metric: "Total Transactions", Value: selectedData?.totalTransactions || 0 },
    ]);
    XLSX.utils.book_append_sheet(wb, ws, "Summary");
    XLSX.writeFile(wb, `analytics-data-${format(new Date(), 'yyyy-MM-dd')}.xlsx`);
  };

  const generateBusinessSummary = async () => {
    const summary = `
📊 *ANALYTICS SUMMARY - HIBAN STORE*

📅 Period: ${timeframe}

💰 *KEY METRICS*
- Total Revenue: *${formatCurrency(selectedData?.totalRevenue || 0)}*
- Total Profit: *${formatCurrency(selectedData?.totalProfit || 0)}*
- Profit Margin: *${(selectedData?.profitMargin || 0).toFixed(1)}%*
- Growth Rate: *${(selectedData?.growthRate || 0) > 0 ? '+' : ''}${(selectedData?.growthRate || 0).toFixed(1)}%*

📈 *INSIGHTS*
- Performance trend: ${(selectedData?.growthRate || 0) > 0 ? 'Positive 📈' : 'Needs attention 📉'}
- Business health: ${(selectedData?.profitMargin || 0) > 20 ? 'Excellent' : (selectedData?.profitMargin || 0) > 10 ? 'Good' : 'Improving'}

─────────────────────
🤖 Generated by Hiban Analytics
⏰ ${format(new Date(), 'dd MMM yyyy, HH:mm')}
    `.trim();

    try {
      await navigator.clipboard.writeText(summary);
      toast.success('Business summary copied to clipboard!');
    } catch (error) {
      const blob = new Blob([summary], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `business-summary-${format(new Date(), 'yyyy-MM-dd')}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center">
            <Download className="h-5 w-5 mr-2 text-primary" />
            Export Analytics Report
          </DialogTitle>
          <DialogDescription>
            Generate comprehensive analytics reports in various formats
          </DialogDescription>
        </DialogHeader>
        
        <div className="space-y-6">
          {/* Export Format Selection */}
          <div className="space-y-3">
            <Label>Export Format</Label>
            <div className="grid grid-cols-2 gap-3">
              {[
                { value: 'pdf', label: 'PDF Report', icon: FileText, desc: 'Complete report with charts' },
                { value: 'png', label: 'Chart Images', icon: Image, desc: 'High-res chart exports' },
                { value: 'excel', label: 'Excel Data', icon: FileSpreadsheet, desc: 'Raw data in spreadsheet' },
                { value: 'summary', label: 'WhatsApp Summary', icon: MessageCircle, desc: 'Quick summary text' }
              ].map((format) => (
                <div
                  key={format.value}
                  className={`p-3 border rounded-lg cursor-pointer transition-colors ${
                    exportFormat === format.value 
                      ? 'border-primary bg-primary/5' 
                      : 'border-border hover:border-primary/50'
                  }`}
                  onClick={() => setExportFormat(format.value as any)}
                >
                  <div className="flex items-center space-x-2 mb-1">
                    <format.icon className="h-4 w-4 text-muted-foreground" />
                    <span className="font-medium text-sm">{format.label}</span>
                  </div>
                  <p className="text-xs text-muted-foreground">{format.desc}</p>
                </div>
              ))}
            </div>
          </div>
          
          {/* Export Options */}
          <div className="space-y-3">
            <Label>Include in Export</Label>
            <div className="space-y-2">
              {[
                { key: 'includeCharts', label: 'Charts & Visualizations' },
                { key: 'includeKPIs', label: 'Key Performance Indicators' },
                { key: 'includeTrends', label: 'Trend Analysis' },
                { key: 'includeInsights', label: 'Business Insights' },
                { key: 'includeRawData', label: 'Raw Data Tables' }
              ].map((option) => (
                <div key={option.key} className="flex items-center space-x-2">
                  <Checkbox
                    checked={exportOptions[option.key as keyof typeof exportOptions]}
                    onCheckedChange={(checked) => 
                      setExportOptions(prev => ({ ...prev, [option.key]: checked }))
                    }
                  />
                  <label className="text-sm">{option.label}</label>
                </div>
              ))}
            </div>
          </div>
          
          {/* Export Actions */}
          <div className="flex justify-between items-center pt-4 border-t">
            <Button variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button onClick={handleExport} disabled={isExporting}>
              {isExporting ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Exporting...
                </>
              ) : (
                <>
                  <Download className="h-4 w-4 mr-2" />
                  Export Report
                </>
              )}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};