// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usnswsdwoofsdrraoszy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzbnN3c2R3b29mc2RycmFvc3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODc1ODgsImV4cCI6MjA2ODE2MzU4OH0.NCmTyPegkOok5C0LoBMO4jj9X7UWlRFcnyV_wprgVek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});